/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:gui_Win:847616:
  appc.background(230);
} //_CODE_:gui_Win:847616:

public void respondYes(GButton source, GEvent event) { //_CODE_:yesButton:271116:
  println("yesButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:yesButton:271116:

public void respondNo(GButton source, GEvent event) { //_CODE_:noButton:257097:
  println("noButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:noButton:257097:

public void toggleResponseEffects(GCheckbox source, GEvent event) { //_CODE_:showResponseEffects:514825:
  println("showResponseEffects - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:showResponseEffects:514825:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  gui_Win = GWindow.getWindow(this, "Controls", 0, 0, 400, 240, JAVA2D);
  gui_Win.noLoop();
  gui_Win.addDrawHandler(this, "win_draw1");
  yesButton = new GButton(gui_Win, 80, 63, 80, 30);
  yesButton.setText("Yes");
  yesButton.addEventHandler(this, "respondYes");
  noButton = new GButton(gui_Win, 240, 60, 80, 30);
  noButton.setText("No");
  noButton.addEventHandler(this, "respondNo");
  showResponseEffects = new GCheckbox(gui_Win, 80, 100, 200, 20);
  showResponseEffects.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showResponseEffects.setText("Display Effects Of Answers");
  showResponseEffects.setOpaque(false);
  showResponseEffects.addEventHandler(this, "toggleResponseEffects");
  questionLabel = new GLabel(gui_Win, 160, 20, 80, 20);
  questionLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  questionLabel.setText("Question: 1");
  questionLabel.setTextBold();
  questionLabel.setOpaque(false);
  gui_Win.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui_Win;
GButton yesButton; 
GButton noButton; 
GCheckbox showResponseEffects; 
GLabel questionLabel; 
